import type { AlbumListen, ParseResult } from "@/lib/types";

/** How many covers the example cloud shows after sampling the pool. */
export const EXAMPLE_CLOUD_SIZE = 50;

/**
 * Preset album pool for the demo path. Names favour well-indexed catalogue
 * titles so Deezer/iTunes previews resolve reliably.
 */
export const EXAMPLE_ALBUM_POOL: AlbumListen[] = [
  { album: "Abbey Road", artist: "The Beatles", listenCount: 140 },
  { album: "Thriller", artist: "Michael Jackson", listenCount: 138 },
  { album: "Rumours", artist: "Fleetwood Mac", listenCount: 132 },
  { album: "The Dark Side of the Moon", artist: "Pink Floyd", listenCount: 130 },
  { album: "Nevermind", artist: "Nirvana", listenCount: 128 },
  { album: "OK Computer", artist: "Radiohead", listenCount: 126 },
  { album: "Blue", artist: "Joni Mitchell", listenCount: 124 },
  { album: "Purple Rain", artist: "Prince", listenCount: 122 },
  { album: "Back in Black", artist: "AC/DC", listenCount: 120 },
  { album: "Lemonade", artist: "Beyoncé", listenCount: 118 },
  { album: "To Pimp a Butterfly", artist: "Kendrick Lamar", listenCount: 116 },
  { album: "Channel Orange", artist: "Frank Ocean", listenCount: 114 },
  { album: "Blond", artist: "Frank Ocean", listenCount: 112 },
  { album: "My Beautiful Dark Twisted Fantasy", artist: "Kanye West", listenCount: 110 },
  { album: "The College Dropout", artist: "Kanye West", listenCount: 108 },
  { album: "good kid, m.A.A.d city", artist: "Kendrick Lamar", listenCount: 106 },
  { album: "Random Access Memories", artist: "Daft Punk", listenCount: 104 },
  { album: "Discovery", artist: "Daft Punk", listenCount: 102 },
  { album: "Currents", artist: "Tame Impala", listenCount: 100 },
  { album: "In Rainbows", artist: "Radiohead", listenCount: 98 },
  { album: "Kid A", artist: "Radiohead", listenCount: 96 },
  { album: "Homogenic", artist: "Björk", listenCount: 94 },
  { album: "Dummy", artist: "Portishead", listenCount: 92 },
  { album: "Mezzanine", artist: "Massive Attack", listenCount: 90 },
  { album: "Kind of Blue", artist: "Miles Davis", listenCount: 88 },
  { album: "A Love Supreme", artist: "John Coltrane", listenCount: 86 },
  { album: "What's Going On", artist: "Marvin Gaye", listenCount: 84 },
  { album: "Songs in the Key of Life", artist: "Stevie Wonder", listenCount: 82 },
  { album: "Off the Wall", artist: "Michael Jackson", listenCount: 80 },
  { album: "Legacy! Legacy!", artist: "Jamila Woods", listenCount: 78 },
  { album: "Ctrl", artist: "SZA", listenCount: 76 },
  { album: "SOS", artist: "SZA", listenCount: 74 },
  { album: "ANTI", artist: "Rihanna", listenCount: 72 },
  { album: "Future Nostalgia", artist: "Dua Lipa", listenCount: 70 },
  { album: "When We All Fall Asleep, Where Do We Go?", artist: "Billie Eilish", listenCount: 68 },
  { album: "Punisher", artist: "Phoebe Bridgers", listenCount: 66 },
  { album: "Melodrama", artist: "Lorde", listenCount: 64 },
  { album: "Pure Heroine", artist: "Lorde", listenCount: 62 },
  { album: "Norman Fucking Rockwell!", artist: "Lana Del Rey", listenCount: 60 },
  { album: "Born to Die", artist: "Lana Del Rey", listenCount: 58 },
  { album: "1989", artist: "Taylor Swift", listenCount: 56 },
  { album: "folklore", artist: "Taylor Swift", listenCount: 54 },
  { album: "After Hours", artist: "The Weeknd", listenCount: 52 },
  { album: "Starboy", artist: "The Weeknd", listenCount: 50 },
  { album: "AM", artist: "Arctic Monkeys", listenCount: 49 },
  { album: "Whatever People Say I Am, That's What I'm Not", artist: "Arctic Monkeys", listenCount: 48 },
  { album: "Is This It", artist: "The Strokes", listenCount: 47 },
  { album: "Turn On the Bright Lights", artist: "Interpol", listenCount: 46 },
  { album: "Funeral", artist: "Arcade Fire", listenCount: 45 },
  { album: "The Suburbs", artist: "Arcade Fire", listenCount: 44 },
  { album: "Yankee Hotel Foxtrot", artist: "Wilco", listenCount: 43 },
  { album: "Illinois", artist: "Sufjan Stevens", listenCount: 42 },
  { album: "Carrie & Lowell", artist: "Sufjan Stevens", listenCount: 41 },
  { album: "For Emma, Forever Ago", artist: "Bon Iver", listenCount: 40 },
  { album: "22, A Million", artist: "Bon Iver", listenCount: 39 },
  { album: "Vespertine", artist: "Björk", listenCount: 38 },
  { album: "Parachutes", artist: "Coldplay", listenCount: 36 },
  { album: "A Rush of Blood to the Head", artist: "Coldplay", listenCount: 35 },
  { album: "Origin of Symmetry", artist: "Muse", listenCount: 34 },
  { album: "Absolution", artist: "Muse", listenCount: 33 },
  { album: "Lateralus", artist: "Tool", listenCount: 32 },
  { album: "Ænima", artist: "Tool", listenCount: 31 },
  { album: "Master of Puppets", artist: "Metallica", listenCount: 30 },
  { album: "Ride the Lightning", artist: "Metallica", listenCount: 29 },
  { album: "The Joshua Tree", artist: "U2", listenCount: 28 },
  { album: "Achtung Baby", artist: "U2", listenCount: 27 },
  { album: "Graceland", artist: "Paul Simon", listenCount: 26 },
  { album: "Bridge Over Troubled Water", artist: "Simon & Garfunkel", listenCount: 25 },
  { album: "Pet Sounds", artist: "The Beach Boys", listenCount: 24 },
  { album: "Revolver", artist: "The Beatles", listenCount: 23 },
  { album: "Sgt. Pepper's Lonely Hearts Club Band", artist: "The Beatles", listenCount: 22 },
  { album: "London Calling", artist: "The Clash", listenCount: 21 },
  { album: "Never Mind the Bollocks, Here's the Sex Pistols", artist: "Sex Pistols", listenCount: 20 },
  { album: "The Rise and Fall of Ziggy Stardust and the Spiders From Mars", artist: "David Bowie", listenCount: 19 },
  { album: "Heroes", artist: "David Bowie", listenCount: 18 },
  { album: "Low", artist: "David Bowie", listenCount: 17 },
  { album: "Hounds of Love", artist: "Kate Bush", listenCount: 16 },
  { album: "The Kick Inside", artist: "Kate Bush", listenCount: 15 },
  { album: "Remain in Light", artist: "Talking Heads", listenCount: 14 },
  { album: "Speaking in Tongues", artist: "Talking Heads", listenCount: 13 },
  { album: "Exile on Main St.", artist: "The Rolling Stones", listenCount: 12 },
  { album: "Sticky Fingers", artist: "The Rolling Stones", listenCount: 11 },
  { album: "Led Zeppelin IV", artist: "Led Zeppelin", listenCount: 10 },
  { album: "Houses of the Holy", artist: "Led Zeppelin", listenCount: 9 },
  { album: "The Blueprint", artist: "Jay-Z", listenCount: 87 },
  { album: "Illmatic", artist: "Nas", listenCount: 85 },
  { album: "Ready to Die", artist: "The Notorious B.I.G.", listenCount: 83 },
  { album: "Enter the Wu-Tang (36 Chambers)", artist: "Wu-Tang Clan", listenCount: 81 },
  { album: "Madvillainy", artist: "Madvillain", listenCount: 79 },
  { album: "Donuts", artist: "J Dilla", listenCount: 77 },
  { album: "Since I Left You", artist: "The Avalanches", listenCount: 75 },
  { album: "Endtroducing.....", artist: "DJ Shadow", listenCount: 73 },
  { album: "Selected Ambient Works 85-92", artist: "Aphex Twin", listenCount: 71 },
  { album: "Untrue", artist: "Burial", listenCount: 69 },
  { album: "LP1", artist: "FKA twigs", listenCount: 67 },
  { album: "MAGDALENE", artist: "FKA twigs", listenCount: 65 },
  { album: "Desire, I Want To Turn Into You", artist: "Caroline Polachek", listenCount: 63 },
  { album: "Fetch the Bolt Cutters", artist: "Fiona Apple", listenCount: 61 },
  { album: "When the Pawn...", artist: "Fiona Apple", listenCount: 59 },
  { album: "Voodoo", artist: "D'Angelo", listenCount: 55 },
  { album: "The Miseducation of Lauryn Hill", artist: "Lauryn Hill", listenCount: 200 },
  { album: "The Score", artist: "Fugees", listenCount: 199 },
  { album: "Aquemini", artist: "Outkast", listenCount: 198 },
  { album: "Stankonia", artist: "Outkast", listenCount: 197 },
  { album: "Speakerboxxx/The Love Below", artist: "Outkast", listenCount: 196 },
  { album: "The Eminem Show", artist: "Eminem", listenCount: 195 },
  { album: "The Marshall Mathers LP", artist: "Eminem", listenCount: 194 },
  { album: "2001", artist: "Dr. Dre", listenCount: 193 },
  { album: "Doggystyle", artist: "Snoop Dogg", listenCount: 192 },
  { album: "All Eyez on Me", artist: "2Pac", listenCount: 191 },
  { album: "Me Against the World", artist: "2Pac", listenCount: 190 },
  { album: "It Was Written", artist: "Nas", listenCount: 189 },
  { album: "The Chronic", artist: "Dr. Dre", listenCount: 188 },
  { album: "Paid in Full", artist: "Eric B. & Rakim", listenCount: 187 },
  { album: "Raising Hell", artist: "Run-DMC", listenCount: 186 },
  { album: "Licensed to Ill", artist: "Beastie Boys", listenCount: 185 },
  { album: "Paul's Boutique", artist: "Beastie Boys", listenCount: 184 },
  { album: "Check Your Head", artist: "Beastie Boys", listenCount: 183 },
  { album: "Enter the Dragon", artist: "Wu-Tang Clan", listenCount: 182 },
  { album: "Only Built 4 Cuban Linx...", artist: "Raekwon", listenCount: 181 },
  { album: "Liquid Swords", artist: "GZA", listenCount: 180 },
  { album: "Supreme Clientele", artist: "Ghostface Killah", listenCount: 179 },
  { album: "The Low End Theory", artist: "A Tribe Called Quest", listenCount: 178 },
  { album: "Midnight Marauders", artist: "A Tribe Called Quest", listenCount: 177 },
  { album: "People's Instinctive Travels and the Paths of Rhythm", artist: "A Tribe Called Quest", listenCount: 176 },
  { album: "De La Soul Is Dead", artist: "De La Soul", listenCount: 175 },
  { album: "3 Feet High and Rising", artist: "De La Soul", listenCount: 174 },
  { album: "Bizarre Ride II the Pharcyde", artist: "The Pharcyde", listenCount: 173 },
  { album: "Dogg Food", artist: "Tha Dogg Pound", listenCount: 172 },
  { album: "Regulate... G Funk Era", artist: "Warren G", listenCount: 171 },
  { album: "The Diary", artist: "Scarface", listenCount: 170 },
  { album: "Ridin' Dirty", artist: "UGK", listenCount: 169 },
  { album: "Southernplayalisticadillacmuzik", artist: "Outkast", listenCount: 168 },
  { album: "ATLiens", artist: "Outkast", listenCount: 167 },
  { album: "The Blueprint 2", artist: "Jay-Z", listenCount: 166 },
  { album: "Reasonable Doubt", artist: "Jay-Z", listenCount: 165 },
  { album: "Life After Death", artist: "The Notorious B.I.G.", listenCount: 164 },
  { album: "Born Again", artist: "The Notorious B.I.G.", listenCount: 163 },
  { album: "Get Rich or Die Tryin'", artist: "50 Cent", listenCount: 162 },
  { album: "The Massacre", artist: "50 Cent", listenCount: 161 },
  { album: "Curtain Call: The Hits", artist: "Eminem", listenCount: 160 },
  { album: "Recovery", artist: "Eminem", listenCount: 159 },
  { album: "Section.80", artist: "Kendrick Lamar", listenCount: 158 },
  { album: "DAMN.", artist: "Kendrick Lamar", listenCount: 157 },
  { album: "Mr. Morale & the Big Steppers", artist: "Kendrick Lamar", listenCount: 156 },
  { album: "2014 Forest Hills Drive", artist: "J. Cole", listenCount: 155 },
  { album: "Born Sinner", artist: "J. Cole", listenCount: 154 },
  { album: "If You're Reading This It's Too Late", artist: "Drake", listenCount: 153 },
  { album: "Take Care", artist: "Drake", listenCount: 152 },
  { album: "Views", artist: "Drake", listenCount: 151 },
  { album: "My Dear Melancholy,", artist: "The Weeknd", listenCount: 150 },
  { album: "Beauty Behind the Madness", artist: "The Weeknd", listenCount: 149 },
  { album: "Nostalgia, Ultra", artist: "Frank Ocean", listenCount: 148 },
  { album: "Endless", artist: "Frank Ocean", listenCount: 147 },
  { album: "Igor", artist: "Tyler, The Creator", listenCount: 146 },
  { album: "Flower Boy", artist: "Tyler, The Creator", listenCount: 145 },
  { album: "Call Me If You Get Lost", artist: "Tyler, The Creator", listenCount: 144 },
  { album: "Chromatica", artist: "Lady Gaga", listenCount: 143 },
  { album: "The Fame Monster", artist: "Lady Gaga", listenCount: 142 },
  { album: "Born This Way", artist: "Lady Gaga", listenCount: 141 },
  { album: "21", artist: "Adele", listenCount: 140 },
  { album: "25", artist: "Adele", listenCount: 139 },
  { album: "30", artist: "Adele", listenCount: 138 },
  { album: "Back to Black", artist: "Amy Winehouse", listenCount: 137 },
  { album: "Frank", artist: "Amy Winehouse", listenCount: 136 },
  { album: "Lioness: Hidden Treasures", artist: "Amy Winehouse", listenCount: 135 },
  { album: "The Fame", artist: "Lady Gaga", listenCount: 134 },
  { album: "Parallel Lines", artist: "Blondie", listenCount: 133 },
  { album: "Radical Optimism", artist: "Dua Lipa", listenCount: 132 },
  { album: "Harry's House", artist: "Harry Styles", listenCount: 131 },
  { album: "Fine Line", artist: "Harry Styles", listenCount: 130 },
  { album: "Divide", artist: "Ed Sheeran", listenCount: 129 },
  { album: "Multiply", artist: "Ed Sheeran", listenCount: 128 },
  { album: "Equals", artist: "Ed Sheeran", listenCount: 127 },
  { album: "Un Verano Sin Ti", artist: "Bad Bunny", listenCount: 126 },
  { album: "YHLQMDLG", artist: "Bad Bunny", listenCount: 125 },
  { album: "El Último Tour Del Mundo", artist: "Bad Bunny", listenCount: 124 },
  { album: "Motomami", artist: "Rosalía", listenCount: 123 },
  { album: "El Mal Querer", artist: "Rosalía", listenCount: 122 },
  { album: "Montero", artist: "Lil Nas X", listenCount: 121 },
  { album: "Planet Her", artist: "Doja Cat", listenCount: 120 },
  { album: "Hot Pink", artist: "Doja Cat", listenCount: 119 },
  { album: "SOUR", artist: "Olivia Rodrigo", listenCount: 118 },
  { album: "GUTS", artist: "Olivia Rodrigo", listenCount: 117 },
  { album: "Happier Than Ever", artist: "Billie Eilish", listenCount: 116 },
  { album: "Hit Me Hard and Soft", artist: "Billie Eilish", listenCount: 115 },
  { album: "Midnights", artist: "Taylor Swift", listenCount: 114 },
  { album: "evermore", artist: "Taylor Swift", listenCount: 113 },
  { album: "Lover", artist: "Taylor Swift", listenCount: 112 },
  { album: "reputation", artist: "Taylor Swift", listenCount: 111 },
  { album: "Red (Taylor's Version)", artist: "Taylor Swift", listenCount: 110 },
  { album: "The Tortured Poets Department", artist: "Taylor Swift", listenCount: 109 },
  { album: "Renaissance", artist: "Beyoncé", listenCount: 108 },
  { album: "BEYONCÉ", artist: "Beyoncé", listenCount: 107 },
  { album: "4", artist: "Beyoncé", listenCount: 106 },
  { album: "B'Day", artist: "Beyoncé", listenCount: 105 },
  { album: "Dangerously in Love", artist: "Beyoncé", listenCount: 104 },
  { album: "Over It", artist: "Summer Walker", listenCount: 103 },
  { album: "Still Over It", artist: "Summer Walker", listenCount: 102 },
  { album: "LANA", artist: "SZA", listenCount: 101 },
];

function shuffleInPlace<T>(items: T[]): T[] {
  for (let i = items.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    const tmp = items[i];
    items[i] = items[j];
    items[j] = tmp;
  }
  return items;
}

/** Random sample from the preset pool (default 50). */
export function sampleExampleAlbums(
  count = EXAMPLE_CLOUD_SIZE
): AlbumListen[] {
  const size = Math.min(count, EXAMPLE_ALBUM_POOL.length);
  return shuffleInPlace([...EXAMPLE_ALBUM_POOL]).slice(0, size);
}

export function buildExampleAlbumParseResult(): ParseResult {
  return {
    kind: "album",
    listens: sampleExampleAlbums(),
    skippedRows: 0,
    sourceLabel: "example cloud",
    issues: [],
  };
}
