/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/bricolaTheme.ts
 * Command: astryx theme build src/theme/bricolaTheme.ts --out src/theme/bricola.css
 * CLI: @astryxdesign/cli@0.6.2
 * Core: @astryxdesign/core@0.6.2
 */

/// <reference path="./bricola.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const neutralIconRegistry: IconRegistry;
export declare const bricolaTheme: DefinedTheme;
